title: "Punto Final Collection"
description: "Colección digital de documentos de la revista Punto Final"
url: "https://gorka350.github.io/PuntoFinal-Site"
source: .
collections:
  objects:
    output: true
